from __future__ import annotations

CATEGORY_NAME_MAP: dict[str, str] = {
    "年报": "category_ndbg_szsh",
    "半年报": "category_bndbg_szsh",
    "一季报": "category_yjdbg_szsh",
    "三季报": "category_sjdbg_szsh",
    "业绩预告": "category_yjygjxz_szsh",
    "权益分派": "category_qyfpxzcs_szsh",
    "董事会": "category_dshgg_szsh",
    "监事会": "category_jshgg_szsh",
    "股东会": "category_gddh_szsh",
    "日常经营": "category_rcjy_szsh",
    "公司治理": "category_gszl_szsh",
    "中介报告": "category_zj_szsh",
    "股权变动": "category_gqbd_szsh",
    "股权激励": "category_gqjl_szsh",
    "补充更正": "category_bcgz_szsh",
    "澄清致歉": "category_cqdq_szsh",
    "风险提示": "category_fxts_szsh",
    "首发": "category_sf_szsh",
    "增发": "category_zf_szsh",
    "配股": "category_pg_szsh",
    "公司债": "category_gszq_szsh",
    "可转债": "category_kzzq_szsh",
    "其他融资": "category_qtrz_szsh",
    "解禁": "category_jj_szsh",
    "特别处理和退市": "category_tbclts_szsh",
    "退市整理期": "category_tszlq_szsh",
}

BOARD_MAP: dict[str, tuple[str, str | None]] = {
    "深主板": ("szse", "sz"),
    "沪主板": ("sse", "sh"),
    "创业板": ("szse", None),
    "科创板": ("sse", None),
    "北交所": ("szse", "bj"),
}

INDUSTRY_LIST: list[str] = [
    "农、林、牧、渔业",
    "采矿业",
    "制造业",
    "电力、热力、燃气及水生产和供应业",
    "建筑业",
    "批发和零售业",
    "交通运输、仓储和邮政业",
    "住宿和餐饮业",
    "信息传输、软件和信息技术服务业",
    "金融业",
    "房地产业",
    "租赁和商务服务业",
    "科学研究和技术服务业",
    "水利、环境和公共设施管理业",
    "居民服务、修理和其他服务业",
    "教育",
    "卫生和社会工作",
    "文化、体育和娱乐业",
    "综合",
]
